version: '3.4'

services:
  frontend:
    build:
      context: ./front
      network: host
      dockerfile: Dockerfile
    image: frontend
    container_name: frontcontainer
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./back
      network: host
      dockerfile: Dockerfile
    image: backend
    container_name: backcontainer
    command:  npm start 
    ports:
      - 4000:4000
    depends_on:
      - mongodb
  mongodb:
    image: mongo

